apiVersion: v1
kind: Service
metadata:
  name: es-http
  namespace: elastic-system
spec:
  type: NodePort
  selector:
    common.k8s.elastic.co/type: elasticsearch
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9200
      targetPort: 9200
      
