
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: es-devsa
  namespace: elastic-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: quickstart-es-http
          servicePort: 9200
    host: es.apps-dev.devsa-rnd.frontiir.net
