apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eck-devsa
  namespace: elastic-system
spec:
  ingressClassName: nginx
  rules:
  - host: eck.apps-dev.devsa-rnd.frontiir.net
    http:
      paths:
      - path: /
        backend:
          serviceName: quickstart-kb-http-new
          servicePort: 5601
