apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim  
spec:
  storageClassName: glusterfs
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 1Gi    
